// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "@/global-components/header/Header";
import Footer from '@/global-components/footer/Footer';
import {SearchVehicleProvider} from '../context/searchVehicleContext/searchVehicleContext'
import {BookingProvider} from '../context/bookingContext/bookingContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ZM Rentals",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/favicon.png", 
  // },
};

// export const metadata = {
//   title: "ZM Rentals",
//   description: "Generated by create next app",
//   icons: {
//     icon: [
//       { url: "/icon.png", type: "image/png", sizes: "32x32" },
//       { url: "/icon.png", type: "image/png", sizes: "192x192" },
//     ],
//     apple: { url: "/icon.png" },
//     shortcut: { url: "/icon.png" },
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        
        <link rel="icon" href="/favicon.png" sizes="any" />
        
      </head>

      <body suppressHydrationWarning style={{ backgroundColor: '#FFFFFF' }} >
        <SearchVehicleProvider>
          <BookingProvider>

          <Header />
          {children}
          <Footer />
          </BookingProvider>
        </SearchVehicleProvider>
      </body>
    </html>
  );
}
